using UnityEditor;
using UnityEngine;

[System.Serializable]
public class TestData : Object
{
    public ModelImporterGenerateMaterials generateMaterials;
    public bool importMaterials;
    public ModelImporterMaterialName materialName;
    public ModelImporterMaterialSearch materialSearch;
    public ModelImporterMaterialLocation materialLocation;
    public float m_GlobalScale;
    public bool isUseFileUnitsSupported;
    public bool importVisibility;
    public bool useFileUnits;
    public bool m_UseFileScale;
    public bool isFileScaleUsed;
    public bool importBlendShapes;
    public bool importCameras;
    public bool importLights;
    public bool addCollider;
    public float normalSmoothingAngle;
    public bool splitTangentsAcrossSeams;
    public bool swapUVChannels;
    public bool weldVertices;
    public bool keepQuads;
    public ModelImporterIndexFormat indexFormat;
    public bool preserveHierarchy;
    public bool generateSecondaryUV;
    public float secondaryUVAngleDistortion;
    public float secondaryUVAreaDistortion;
    public float secondaryUVHardAngle;
    public float secondaryUVPackMargin;
    public ModelImporterGenerateAnimations generateAnimations;
    public TakeInfo[] importedTakeInfos;
    public string[] transformPaths;
    public bool isReadable;
    public bool optimizeMesh;
    public ModelImporterTangentSpaceMode normalImportMode;
    public ModelImporterTangentSpaceMode tangentImportMode;
    public ModelImporterNormals importNormals;
    public ModelImporterNormalCalculationMode normalCalculationMode;
    public ModelImporterTangents importTangents;
    public bool bakeIK;
    public bool isBakeIKSupported;
    public bool resampleRotations;
    public bool resampleCurves;
    public bool isTangentImportSupported;
    public ModelImporterMeshCompression meshCompression;
    public int internal_meshCompression;
    public bool importAnimation;
    public bool optimizeGameObjects;
    public string[] extraExposedTransformPaths;
    public string[] extraUserProperties;
    public ModelImporterAnimationCompression animationCompression;
    public bool importAnimatedCustomProperties;
    public bool importConstraints;
    public float animationRotationError;
    public float animationPositionError;
    public float animationScaleError;
    public WrapMode animationWrapMode;
    public ModelImporterAnimationType animationType;
    public ModelImporterHumanoidOversampling humanoidOversampling;
    public string motionNodeName;
    public Avatar sourceAvatar;
    public HumanDescription humanDescription;
    public ModelImporterClipAnimation[] clipAnimations;
    public ModelImporterClipAnimation[] defaultClipAnimations;
}